use std::error::Error;

pub fn main() -> Result<(), Box<dyn Error>> {
    println!("02-1:");
    println!("Work in progress.");

    Ok(())
}
