use std::error::Error;

pub fn main() -> Result<(), Box<dyn Error>> {
    println!("04-1:");
    println!("Work in progress");

    Ok(())
}
